@host = http://localhost:7000/api/v1/usuario 
###
GET {{host}}/1

###
POST {{host}}
content-type: application/json

{
    "nome":"frankli",
    "sobrenome": "frankln",
    "email": "frankln",
    "usuarioNome": "franlin",
    "senha": "frankin"
 }

####
PUT {{host}}/1
content-type: application/json

{
    "nome":"f1",
    "sobrenome": "frankln",
    "email": "frankln",
    "usuarioNome": "franlin",
    "senha": "frankin"
 }

####
DELETE {{host}}/1
Content-Type: application/json
