@host = http://localhost:7000/api/v1/usuario 
###
GET {{host}}/1

###
POST {{host}}
content-type: application/json

{
    "nome":"f",
    "sobrenome": "f",
    "email": "@outlook.com",
    "usuarioNome": "f",
    "senha": "123"
 }

####
PUT {{host}}/1
content-type: application/json

{
    "nome":"f1",
    "sobrenome": "f1",
    "email": "@outlook.com",
    "usuarioNome": "f1",
    "senha": "1234"
 }

####
DELETE {{host}}/1
Content-Type: application/json
